name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Set up SSH authentication for GitHub
            echo "${{ secrets.HNG }}" > ~/.ssh/hng
            chmod 600 ~/.ssh/hng
            eval $(ssh-agent)
            ssh-add ~/.ssh/hng
            
            cd ~/fastapi-book-project || exit 1
            
            echo "Pulling latest code from GitHub"
            git pull origin main || exit 1
            
            echo "Activating virtual environment"
            source ~/fastapi-book-project/venv/bin/activate
            
            echo "Installing dependencies"
            pip install -r requirements.txt
            
            echo "Restarting FastAPI app"
            sudo systemctl restart fastapi-app
            
            echo "Deployment completed successfully"

      - name: Finish deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: http://ec2-44-208-163-66.compute-1.amazonaws.com