name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project || exit 1
            
            echo "Pulling latest code from GitHub"
            git pull origin main || exit 1
            
            echo "Activating virtual environment"
            source /home/ubuntu/fastapi-book-project/venv/bin/activate
            
            echo "Installing dependencies"
            pip install -r requirements.txt
            
            echo "Restarting FastAPI app"
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi-app
            
            echo "Deployment completed successfully"
