name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key and GitHub SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > hng-stage-2.pem || exit 1
          
          chmod 600 hng-stage-2.pem
          
          echo "${{ secrets.HNG }}" > hng
          
          chmod 600 hng
          
          eval "$(ssh-agent -s)"
          
          ssh-add hng
          
          ssh-add -l

      - name: Deploy to EC2 Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i hng-stage-2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST || 'ec2-44-208-163-66.compute-1.amazonaws.com' }} << 'EOF'
            cd fastapi-book-project || exit 1
            git pull origin main || exit 1
            source venv/bin/activate || exit 1
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
          EOF
